
        BEGIN
            EXECUTE IMMEDIATE 'DROP TRIGGER audit_USUARIOS_trg';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -4080 THEN
                    RAISE;
                END IF;
        END;
        

    CREATE OR REPLACE TRIGGER audit_USUARIOS_trg
    AFTER INSERT OR UPDATE OR DELETE ON USUARIOS
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
            VALUES ('USUARIOS', USER, 'INSERT', :NEW.USUARIO_ID || ',' || :NEW.NOMBRE || ',' || :NEW.APELLIDO || ',' || :NEW.EMAIL || ',' || :NEW.FECHA_REGISTRO);
        ELSIF UPDATING THEN
            INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
            VALUES ('USUARIOS', USER, 'UPDATE', :NEW.USUARIO_ID || ',' || :NEW.NOMBRE || ',' || :NEW.APELLIDO || ',' || :NEW.EMAIL || ',' || :NEW.FECHA_REGISTRO);
        ELSIF DELETING THEN
            INSERT INTO AUDITORIA (NOMBRE_TABLA, USUARIO_DB, ACCION, DESCRIPCION_CAMBIOS)
            VALUES ('USUARIOS', USER, 'DELETE', :OLD.USUARIO_ID || ',' || :OLD.NOMBRE || ',' || :OLD.APELLIDO || ',' || :OLD.EMAIL || ',' || :OLD.FECHA_REGISTRO);
        END IF;
    END;
    
